[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "cd backend && npx prisma generate && npx prisma migrate deploy && node ./dist/main.js"
healthCheckPath = "/"
